---
deployment:
  tasks:
    - export DEPLOYPATH=/home/skdssite/public_html
    - /bin/cp -R *.html $DEPLOYPATH
    - /bin/cp -R *.php $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R php $DEPLOYPATH
